# Generated by Django 2.0.3 on 2018-04-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='filename',
            field=models.FileField(default=123, upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
