# Generated by Django 2.0.3 on 2018-04-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20180406_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='type',
            field=models.CharField(choices=[('Пейзаж', 'Пейзаж'), ('Натюрморт', 'Натюрморт'), ('Портрет', 'Портрет'), ('Ню', 'Ню')], default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
