# Generated by Django 2.0.3 on 2018-04-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20180407_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='height',
            new_name='p_height',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='image',
            new_name='p_image',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='in_stock',
            new_name='p_in_stock',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='name',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='price',
            new_name='p_price',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='type',
            new_name='p_type',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='width',
            new_name='p_width',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='year',
            new_name='p_year',
        ),
    ]
