# Generated by Django 2.0.3 on 2018-04-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20180412_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='p_height',
            field=models.CharField(max_length=15, verbose_name='Высота:'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='p_image',
            field=models.ImageField(upload_to='', verbose_name='Изображение:'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='p_in_stock',
            field=models.BooleanField(default=True, verbose_name='Жанр:'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='p_name',
            field=models.CharField(max_length=200, verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='p_price',
            field=models.IntegerField(verbose_name='Цена:'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='p_type',
            field=models.CharField(choices=[('Пейзаж', 'Пейзаж'), ('Натюрморт', 'Натюрморт'), ('Портрет', 'Портрет'), ('Ню', 'Ню')], max_length=40, verbose_name='Жанр:'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='p_width',
            field=models.CharField(max_length=15, verbose_name='Ширина:'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='p_year',
            field=models.CharField(max_length=4, verbose_name='Год:'),
        ),
    ]
